name: Update Wiki
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: # needed to write to wiki repository with just the workflow's access token rather than PAT
  contents: write
  pages: write


jobs:
  test:
    strategy:
      matrix:
        #        os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v4
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Nuke CI
        shell: pwsh
        run: ./build_nuke.ps1
      - name: debug
        if: always()
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true